### ISSUE TITLE
Can not grunt build with slidebars

### ISSUE THREAD

**Issue by khacluan** [adchsm/Slidebars#155]
I tried add slidebars in bower.json and install it, but when I grunt build it not automatic add js file to index.html file.
This is error:
`slidebars was not injected in your file.`

**Comment by lsiric** [comment]
Hi @khacluan ,

per this answer here : http://stackoverflow.com/a/29052764, your latest tag (0.10.3) is missing `main` entry in your `bower.json` file. I can see it in the master branch, but the **latest** tag does not have it.

That's why grunt-wiredep, or any other automatic-dependency-injectors can't automatically inject Slidebars. 

Unfortunately, who ever got Slidebars installed with bower, and is using any of the modern task runners with auto-bower-packages-injection will probably have the same problem.

Cheers, 

Luka
