### ISSUE TITLE
Can I keep side bar open responsively?

### ISSUE THREAD

**Issue by whoever123** [adchsm/Slidebars#162]
Similar to disableOver:480, something like leftopenOver:768

Thanks.

**Comment by adchsm** [comment]
Hi there,

Slidebars isn't really designed to be open permanently, as it pushes content off the screen, rather than resizing the content area.

I would suggest creating a menu that is simply shown over screen width you want, and disabling Slidebars over that width too.

I hope that helps,

Thanks, Adam

**Comment by Anke** [comment]
Hi Adam,

I CSSed my content area to resize rather than to be pushed out of sight. Did I get this right - there's no built-in option to leave the desktop slidebar open (across pages) until closed manually?

Best regards,
Anke
