### ISSUE TITLE
Slidebar closes when clicking inside of open slidebar

### ISSUE THREAD

**Issue by mikerodriguez** [adchsm/Slidebars#164]
First off, just want to thank you for this awesome project, I, as well as many developers out there, appreciate your work on the Slidebars project. It's one of the best out there.

I'm having a weird issue that closes an open slide bar whenever I'm click inside of the slidebar. the issue occurs whenever I click (or tap, on mobile) on any element inside of the open slidebar. 

For example, I have a search input field that closes the sidebar when clicked on. Also, links inside the Slidebar are not working, for some odd reason. 

I site want the slidebar to close when the user taps away from the slidebar (clicks or taps onto #sb-site) so disabling the siteClose option is not a solution. 

Click here for demo >> http://dev.mikerodriguez.me/ 

If you can shed some light on this issue, I would appreciate it. Thanks.

I'm using the latest version of Slidebars + jQuery 1.11.0. And i've tested on majors browser (Chrome, Firefox, Safari) on a mac as well as on iOS 8 Safari

**Comment by adchsm** [comment]
Thanks I'm glad you like the plugin :)

It might be down to the development version. Try using version 0.10.2 in the distribution folder. The dev version is messy, and well, in development. Last time I spent some time with it I was playing with some click events so it could be that.

Try changing that and let me know if it works. Otherwise your markup looks perfect.

Thanks, Adam

**Comment by mikerodriguez** [comment]
Adam,

You were right. I was using the dev version. Just switched it over to the distribution version and everything is working great. Thanks for the tip. Again, I appreciate all your work on this project. 

Thanks mate,
Mike

**Comment by adchsm** [comment]
No problem, glad that sorted it :)
