### ISSUE TITLE
<html>.sb-scroll-lock class not working on Android

### ISSUE THREAD

**Issue by Kimdarry** [adchsm/Slidebars#173]
Hey Adam
First of all, this plugin you worked on is really great!

I think this is by far the best slide plugin that i have ever seen.

However, I did have a question that I was hoping you could answer.

It seems like the '.sb-scroll-lock' class is not working as intended, or it may simply be that I am making a mistake

This class works well on the iOS but there seems to be a compatibility issue with the AndroidOS.

The contents in the background scroll with the slide bar.

For your information, the .sb-scroll-lock class is currently connected to the <html> tag.

Is there a way to make this work on the AndroidOS?

Thanks!!!

**Comment by adchsm** [comment]
Hey there,

Thanks :) I'm glad to here you like the plugin.

Yeah scroll locking currently only works on desktops, any mobile devices it works on is luckily.

I'm not currently developing Slidebars at the moment, so there wont be any updates or fixes I'm afraid.

This issue was also listed here: https://github.com/adchsm/Slidebars/issues/131

There is a potential fix there, but I haven't looked into it yet.

Sorry I can't be of more help,

Thanks, Adam

**Comment by adchsm** [comment]
This should be fixed in the new development version of 2.0.

**Comment by philipsacht** [comment]
when will 2.0 be stable?

**Comment by adchsm** [comment]
Hi philipsacht,

I've just released Slidebars 2 today, check out [adchsm.com/slidebars](http://www.adchsm.com/slidebars/) for more info and usage instructions.

Thanks,

Adam
