### ISSUE TITLE
Problem with jQuery sroll to element

### ISSUE THREAD

**Issue by NOTIFcms** [adchsm/Slidebars#184]
Hi, Can you help me with **jQuery animate()**? I have a problem with jQuery sroll to element. So, When I insert *slibars.css* into HTML page, the jQuery sroll to element does´t working.

[Link to JSFIDDLE.] (https://jsfiddle.net/k2695v18/54/)
After click on Scroll down Back to top, nothing will happened.

But, When I remove CSS, everythink is allright. Can you help mi with this problem please?

Tomas

**Comment by adchsm** [comment]
Hey!

Nice to see you using the new beta :)

Yep the problem is occurring as the html and body are both set to 100% height, so there is no where to scroll. The actually scrolling of the site is located inside the `canvas="container"`.

So instead of animating the html and body like this:

```
$('a[href^="#"]').on('click', function(event) {
  var target = $( $(this).attr('href') );
  if( target.length ) {
    event.preventDefault();
    $('html, body').animate({
      scrollTop: target.offset().top
    }, 1000);
  }
});
```

We can just change `html, body` to `#top` which is the id of your canvas container:

```
$('a[href^="#"]').on('click', function(event) {
  var target = $( $(this).attr('href') );
  if( target.length ) {
    event.preventDefault();
    $('#top').animate({
      scrollTop: target.offset().top
    }, 1000);
  }
});
```

... and that should do it, take a look here:

https://jsfiddle.net/k2695v18/55/

Thanks for bringing this to my attention though, i'll be sure to write an article on it to add to the Help Center!

Adam
