### ISSUE TITLE
elements with fixed position disappers 

### ISSUE THREAD

**Issue by getnathans** [adchsm/Slidebars#222]
Hi
If $(window).scroll(function(){} is used to fix position of certain elements on the screen then scroll function will not work properly when we use this slider.
The problem is between line 203 and 228 in your slidebars.css.

If you want to replicate this issue just add $(window).scroll(function () {} and try to fix the position of a div on the screen. Then you will it is impossible to maintain the position of that element just because scroll function no longer works. But if you remove the line from 203 to 228 in your slidebars.css then scrolling and positioning work but sliding menu stops.

This is an issue with most of the push sliders but I thought its not happening in yours. Unfortunately this slider has the same issue.

cheers
Nathan

**Comment by adchsm** [comment]
Hi Nathan,

Are you just using `.scroll()` for a fixed positioned element? If so there are workaround for using that with CSS: http://plugins.adchsm.me/slidebars/issues/fixed-position.php

Otherwise if you need to use `.scroll()` maybe you could targeting `$( '#sb-site' )` instead of `$( window )`.

Let me know if that helps, or if you can supply at JSFiddle, I'll take closer look.

Thanks,

Adam
