### ISSUE TITLE
sb-slide

### ISSUE THREAD

**Issue by itgnet** [adchsm/Slidebars#47]
Hey Adam, thanks for your great plugin. I'm facing a little problem with the sb-style-overlay. I want to translate the menubutton which is position fixed to the left together with the overlay. Unfortunately the sb-slide class doesn't move the button.
this is the code i'm using for the button:

```
<div class="lbtn btn-menu pointer sb-toggle-left sb-slide">button</div>
```

and for the slidebar:

```
<div class="sb-slidebar sb-left sb-width-wide sb-style-overlay">slidebar content</div>
```

Would appreciate any help

**Comment by gabriellima** [comment]
Hey there. I'm facing a similar problem.
I'm using the newest version, and as this is an old issue, I'd like to know if there was any upgrade to include a behaviour similar to this. Or, otherwise, how I'd approach a similar solution.

I have a left menu button (glyphicon-cog), which is position fixed, that I need to translate together with a left panel overlay. It would be similar to [Toogle overlay](https://www.adchsm.com/slidebars/demos/animation-styles/) together with a behaviour like this [demo page](http://www.jqueryscript.net/demo/Sliding-Side-Menu-Panel-with-jQuery-Bootstrap-BootSideMenu/).

I.e., when I click the menu button, the slidebar appears in overlay, but brings with it the menu button, so that the user can click it to close the panel.

In the final version, I'll have three menu buttons aligned vertically, with Multiple Same Side Slidebars, where each button toggle it's respective slidebar.

Thank you in advance.
